name: ${project.artifactId}
version: '${project.version}'
main: ${project.groupId}.${project.artifactId}
api-version: ${minecraft.api-version}
authors: [ freethemice ]
description: ${project.description}
website: ${project.url}
softdepend:
  - Vault
commands:
  titanguide:
    description: titanguide
    usage: /<command>
  tguide:
    description: titanguide
    usage: /<command>
  titan:
    description: titanguide
    usage: /<command>